### ISSUE TITLE
Prometheus not digesting properly derived Labels

### ISSUE THREAD

**Issue by adrianpadurean** [fhemberger/mqtt_exporter#13]
```python
 # Add derived metric for when the message was last received (timestamp in milliseconds)
        derived_metric = {
            'name': f"{metric['name']}_last_received",
            'help': f"Last received message for '{metric['name']}'",
            'type': metric['type']
        }
        derived_labels = {'topic': metric['topic'],
                          'value': int(round(time.time() * 1000))}

        _export_to_prometheus(metric['name'], metric, labels)

        _export_to_prometheus(
            derived_metric['name'], derived_metric, derived_labels)
```

This results in a error being thrown by the Prometheus component in the vendor
```
2021-05-19 15:53:44,935 DEBUG: _on_message Msg received on topic: test/eth-ldr-1/temperature1, Value: b'26.875'
2021-05-19 15:53:44,935 DEBUG: _topic_matches: Topic1: test/+/temperature1, Topic2: test/eth-ldr-1/temperature1
2021-05-19 15:53:44,935 DEBUG: _topic_matches: Match: True
2021-05-19 15:53:44,935 DEBUG: _update_metrics all labels:
2021-05-19 15:53:44,935 DEBUG: {'__topic__': 'test/+/temperature1', '__msg_topic__': 'test/eth-ldr-1/temperature1', '__value__': 26.875}
2021-05-19 15:53:44,936 DEBUG: PRE - _export_to_prometheus metric (counter): eth_ldr{'topic': 'test/+/temperature1'} updated with value: 27.4740262964
2021-05-19 15:53:44,936 DEBUG: _export_to_prometheus metric (counter): eth_ldr{'topic': 'test/+/temperature1'} updated with value: 27.4740262964
2021-05-19 15:53:44,936 DEBUG: PRE - _export_to_prometheus metric (counter): eth_ldr_last_received{'topic': 'test/+/temperature1'} updated with value: 1621432424936.41
Traceback (most recent call last):
  File "./mqtt_exporter.py", line 473, in <module>
    main()
  File "./mqtt_exporter.py", line 469, in main
    mqtt_client.loop_forever()
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "./mqtt_exporter.py", line 307, in _on_message
    _update_metrics(userdata[topic], msg)
  File "./mqtt_exporter.py", line 295, in _update_metrics
    _export_to_prometheus(
  File "./mqtt_exporter.py", line 358, in _export_to_prometheus
    prometheus_metric_types[metric['type'].lower()](
  File "./mqtt_exporter.py", line 397, in counter
    get_prometheus_metric(label_names, label_values, metric, name).inc(value)
  File "./mqtt_exporter.py", line 386, in get_prometheus_metric
    metric['prometheus_metric']['base'] = prometheus_metric_types[metric_type](name, metric['help'],
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/metrics.py", line 121, in _init_
    registry.register(self)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/registry.py", line 29, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'eth_ldr_last_received_created', 'eth_ldr_last_received', 
```

While I checked, the value of the metric is different than previous iterations.

```
2021-05-19 16:32:29,484 DEBUG: {'__topic__': 'test/+/temperature1', '__msg_topic__': 'test/eth-ldr-1/temperature1', '__value__': 26.875}
2021-05-19 16:32:29,485 DEBUG: _update_metrics all labels --- DERIVED:
2021-05-19 16:32:29,485 DEBUG: {'topic': 'test/+/temperature1', 'value': 1621434749485}
2021-05-19 16:32:29,485 DEBUG: _export_to_prometheus metric (gauge): eth_ldr{'topic': 'test/+/temperature1'} updated with value: 26.875
2021-05-19 16:32:29,485 DEBUG: _export_to_prometheus metric (gauge): eth_ldr_last_received{'topic': 'test/+/temperature1'} updated with value: 1621434749485
2021-05-19 16:32:30,100 DEBUG: _on_message Msg received on topic: test/eth-ldr-1/temperature1, Value: b'26.8125'
2021-05-19 16:32:30,100 DEBUG: _topic_matches: Topic1: test/+/temperature1, Topic2: test/eth-ldr-1/temperature1
2021-05-19 16:32:30,101 DEBUG: _topic_matches: Match: True
2021-05-19 16:32:30,101 DEBUG: _update_metrics all labels:
2021-05-19 16:32:30,101 DEBUG: {'__topic__': 'test/+/temperature1', '__msg_topic__': 'test/eth-ldr-1/temperature1', '__value__': 26.8125}
2021-05-19 16:32:30,101 DEBUG: _update_metrics all labels --- DERIVED:
2021-05-19 16:32:30,102 DEBUG: {'topic': 'test/+/temperature1', 'value': 1621434750102}
2021-05-19 16:32:30,102 DEBUG: _export_to_prometheus metric (gauge): eth_ldr{'topic': 'test/+/temperature1'} updated with value: 26.8125
```

The error itself might not be from the exporter itself but from the data source/data digestion, do you have any hints?

**Comment by fhemberger** [comment]
Sorry it took so long to get back to you, didn't get any notifications for this repo. 😠 

Thanks for reporting, I'll look into it. In the meantime, I'd recommend to try going back to v1.1 and see if it works for you.

**Comment by fhemberger** [comment]
Sorry, I'm having trouble reproducing that issue with my local MQTT/exporter setup.

I updated the dependencies (including `prometheus_client`) and set the derived metrics to always be of type `Gauge`. Could you please check if the problem still occurs?

**Comment by poggenpower** [comment]
I think this is a dupplicate of https://github.com/fhemberger/mqtt_exporter/issues/15 and should be fixed with: 
https://github.com/fhemberger/mqtt_exporter/releases/tag/v1.2.3
